#!/usr/bin/env bash
# Load test in two parts, each reporting what it measured on the machine it ran on.
#
#  1. Broker capacity: Kafka's own producer benchmark, 400-byte records (about one telemetry
#     event) into a scratch topic with the same 24 partitions as telemetry.raw.
#  2. End to end: the simulator bursts (every vehicle reports k times per interval) and we
#     measure, every 10 s, events generated by the simulator and rows landing in ClickHouse.
#
#   tests/load/throughput.sh [burst-factor] [seconds]     (defaults 10 and 120)
set -euo pipefail

K=${1:-10}
SECS=${2:-120}
SIM=${SIM_URL:-http://localhost:8090}
CH=${CH_URL:-http://localhost:8123}
CH_AUTH=${CH_AUTH:-fleet:clickhouse_dev}
KAFKA=${KAFKA_CONTAINER:-fleetpulse-kafka-1}
PY=${PYTHON:-python3}
OUT=tests/load/results/throughput-$(date -u +%Y%m%dT%H%M%SZ).txt
mkdir -p "$(dirname "$OUT")"
log() { echo "$*" | tee -a "$OUT"; }
json() { $PY -c "import json,sys; d=json.load(sys.stdin); print($1)"; }

log "== 1. Kafka broker capacity (kafka-producer-perf-test, 2,000,000 x 400 B, acks=all, 24 partitions)"
docker exec "$KAFKA" /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists \
  --topic loadtest.scratch --partitions 24 --replication-factor 1 >/dev/null
docker exec "$KAFKA" /opt/kafka/bin/kafka-producer-perf-test.sh --topic loadtest.scratch --num-records 2000000 \
  --record-size 400 --throughput -1 --producer-props bootstrap.servers=localhost:9092 acks=all linger.ms=10 \
  batch.size=262144 compression.type=lz4 | tail -1 | tee -a "$OUT"
docker exec "$KAFKA" /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --delete --topic loadtest.scratch

stats() { curl -fsS "$SIM/admin/stats"; }
generated() { stats | json "sum(d['ledgerValidUnique'].values())"; }
stored() { curl -fsS --user "$CH_AUTH" --data-binary "SELECT count() FROM fleet.telemetry WHERE ingest_ts > now() - INTERVAL 1 DAY" "$CH/"; }

VEH=$(stats | json "d['vehicles']"); INT=$(stats | json "d['intervalSeconds']")
log ""
log "== 2. End to end: $VEH vehicles every ${INT}s, burst x$K => target $((VEH * K / INT)) events/s, for ${SECS}s"
curl -fsS -X POST "$SIM/admin/burst?factor=$K&seconds=$SECS" >/dev/null
g0=$(generated); s0=$(stored); t0=$(date +%s)
printf '%-6s %14s %14s %12s\n' "t(s)" "generated/s" "stored/s" "backlog" | tee -a "$OUT"
pg=$g0; ps=$s0; pt=$t0
while [ $(( $(date +%s) - t0 )) -lt "$SECS" ]; do
  sleep 10
  g=$(generated); s=$(stored); t=$(date +%s); dt=$((t - pt))
  printf '%-6s %14s %14s %12s\n' "$((t - t0))" "$(( (g - pg) / dt ))" "$(( (s - ps) / dt ))" "$(( (g - g0) - (s - s0) ))" | tee -a "$OUT"
  pg=$g; ps=$s; pt=$t
done
g=$(generated); s=$(stored); t=$(date +%s)
log "average: generated $(( (g - g0) / (t - t0) ))/s, stored $(( (s - s0) / (t - t0) ))/s over $((t - t0))s"
log "report: $OUT"
